### PR TITLE
Design Changed and useContext format added and context providers

### PR DESCRIPTION
**Pull request by calebmutisya**
Changed Title name to FocusTimer
Added Home Button in Navbar
Added UserContext,Taskscontext and Reportcontext.
Added context Providers to App.js

### CODE REVIEW

**Comment by FLAWIN** [comment]
Title name changed to FocusTimer .
Contexts added.

**Comment by calebmutisya** [comment]
Done

**Comment by Wanguba** [comment]
Home button added in the navbar
Context Providers added to App.js

**Comment by Albright-tech** [comment]
Great job on the frontend! The UI looks clean and user-friendly
I appreciate how well-organized and modular your code is. It makes it easy to follow and maintain.
I like your use of meaningful variable and function names. It makes the code self-explanatory

**Pull request merged**
